// TODO: Replace with proper i18n translation system (e.g., next-intl, i18next)

/**
 * Application-wide constants and multilingual text content
 * Supports: English (en), Japanese (ja), Chinese (cn)
 */

export type Language = "en" | "ja" | "zh-CN" | "zh-TW";

export const APP_CONSTANTS = {
  // Validation limits
  MAX_TITLE_LENGTH: 200,
  MAX_CONTENT_LENGTH: 10000,
  MAX_COMMENT_LENGTH: 2000,
  MAX_NAME_LENGTH: 50,
  MIN_PASSWORD_LENGTH: 6,
  USER_ID_MAX_LENGTH: 12,
  USER_ID_MIN_LENGTH: 1,
  USER_ID_REGEX: /^[a-zA-Z0-9]{1,12}$/,
  USER_NAME_MAX_LENGTH: 50,
  USER_NAME_MIN_LENGTH: 2,
  USER_NICKNAME_MAX_LENGTH: 20,
  USER_EMAIL_MAX_LENGTH: 255,
  USER_EMAIL_MIN_LENGTH: 3,
  USER_EMAIL_REGEX: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  USER_PASSWORD_MAX_LENGTH: 32,
  USER_PASSWORD_MIN_LENGTH: 6,

  // Pagination
  POSTS_PER_PAGE: 20,
  COMMENTS_PER_PAGE: 10,

  // File upload
  MAX_AVATAR_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_IMAGE_TYPES: ["image/jpeg", "image/png", "image/webp", "image/gif"],

  // Categories (internal keys)
  POST_CATEGORIES: [
    "general",
    "question",
    "discussion",
    "announcement",
  ] as const,

  // User roles (internal keys)
  USER_ROLES: {
    ADMIN: "admin",
    USER: "user",
  },
} as const;

// Multilingual text content
export const TRANSLATIONS = {
  en: {
    // Application info
    APP_NAME: "Boxing Buddies World",
    APP_SHORT_NAME: "BBW",
    APP_DESCRIPTION:
      "A boxing community for boxing buddies to share their thoughts and experiences worldwide.",

    // Home page
    HOME_WELCOME: "Welcome to BBW",
    HOME_SUBTITLE: "Share your thoughts, connect with others",
    HOME_NO_POSTS: "No posts yet",
    HOME_CREATE_FIRST_POST: "Create the first post",

    // Common actions
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    SUBMIT: "Submit",
    LOADING: "Loading...",
    REPLY: "Reply",
    LIKE: "Like",
    VIEW: "View",
    SHARE: "Share",
    SEE_MORE: "See more",

    // Admin Management
    POSTS_MANAGEMENT: "Posts Management",
    USERS_MANAGEMENT: "Users Management",
    CATEGORIES_MANAGEMENT: "Categories Management",
    TOTAL: "Total",
    AUTHOR: "Author",
    CREATED: "Created",
    ACTIONS: "Actions",
    NO_POSTS_FOUND: "No posts found",
    FAILED_TO_LOAD_POSTS: "Failed to load posts",
    POST_DELETED_SUCCESS: "Post deleted successfully",
    FAILED_TO_DELETE_POST: "Failed to delete post",
    PREVIOUS: "Previous",
    NEXT: "Next",
    PAGE: "Page",
    OF: "of",

    // Alert Dialog
    ARE_YOU_SURE: "Are you sure?",
    DELETE_POST_CONFIRMATION:
      "This action cannot be undone. This will permanently delete the post and all its comments.",
    ALERT_CANNOT_BE_UNDONE: "This action cannot be undone.",
    ALERT_USER_ID_REQUIRED: "User ID is required",
    ALERT_PASSWORD_REQUIRED: "Password is required",
    ALERT_USER_ID_CAN_ONLY_CONTAIN_ENGLISH_LETTERS_AND_NUMBERS:
      "User ID can only contain English letters and numbers",
    ALERT_INVALID_EMAIL_ADDRESS: "Invalid email address",
    ALERT_NAME_MIN_LENGTH: "Name must be at least 2 characters",
    ALERT_NAME_MAX_LENGTH: "Name must be 50 characters or less",
    ALERT_NICKNAME_MAX_LENGTH: "Nickname must be 20 characters or less",
    ALERT_EMAIL_REQUIRED: "Email is required",
    ALERT_EMAIL_TAKEN: "This email is already taken",
    ALERT_PASSWORD_MIN_LENGTH: "Password must be at least 6 characters",
    ALERT_PASSWORD_MAX_LENGTH: "Password must be 32 characters or less",
    ALERT_SLUG_REQUIRED: "Slug is required",
    ALERT_SLUG_MUST_BE_LOWERCASE_ALPHANUMERIC_WITH_HYPHENS:
      "Slug must be lowercase alphanumeric with hyphens",
    ALERT_NAME_REQUIRED: "Name is required",
    ALERT_TITLE_REQUIRED: "Title is required",
    ALERT_CONTENT_REQUIRED: "Content is required",
    ALERT_CATEGORY_REQUIRED: "Category is required",
    ALERT_DESCRIPTION_MAX_LENGTH: "Description must be 1000 characters or less",
    ALERT_DISPLAY_ORDER_MIN: "Display order must be 0 or greater",
    ALERT_DISPLAY_ORDER_MAX: "Display order must be 1000 or less",

    // Error messages
    ERROR_GENERIC: "Something went wrong. Please try again.",
    ERROR_UNAUTHORIZED: "You are not authorized to perform this action.",
    ERROR_NOT_FOUND: "The requested resource was not found.",
    ERROR_INVALID_INPUT: "Invalid input. Please check your data.",
    ERROR_NETWORK: "Network error. Please check your connection.",

    // Loading messages
    LOADING_POSTS: "Loading posts...",
    LOADING_COMMENTS: "Loading comments...",
    LOADING_USERS: "Loading users...",
    LOADING_CATEGORIES: "Loading categories...",
    LOADING_PROFILE: "Loading profile...",
    LOADING_ADMIN_DASHBOARD: "Loading admin dashboard...",
    LOADING_ADMIN_CATEGORIES: "Loading admin categories...",
    LOADING_ADMIN_POSTS: "Loading admin posts...",
    LOADING_ADMIN_USERS: "Loading admin users...",

    // Success messages
    SUCCESS_SAVED: "Successfully saved!",
    SUCCESS_DELETED: "Successfully deleted!",
    SUCCESS_UPDATED: "Successfully updated!",
    SUCCESS_CREATED: "Successfully created!",

    // Categories
    CATEGORY_GENERAL: "General",
    CATEGORY_QUESTION: "Question",
    CATEGORY_DISCUSSION: "Discussion",
    CATEGORY_ANNOUNCEMENT: "Announcement",

    // User roles
    ROLE_ADMIN: "Admin",
    ROLE_USER: "User",

    // Auth
    LOGIN: "Login",
    LOGOUT: "Logout",
    REGISTER: "Register",
    EMAIL: "Email",
    PASSWORD: "Password",
    USERNAME: "Username",
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
    DONT_HAVE_ACCOUNT: "Don't have an account?",

    // Register Form
    CREATE_ACCOUNT: "Create an account",
    ENTER_DETAILS_TO_REGISTER: "Enter your details to register",
    USERNAME_PLACEHOLDER: "Max 12 alphanumeric characters",
    USER_ID_TAKEN: "This User ID is already taken",
    USER_ID_AVAILABLE: "User ID is available",
    NAME_LABEL: "Name",
    NICKNAME_LABEL: "Nickname (Optional)",
    CONFIRM_PASSWORD: "Confirm Password",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    GENDER_OPTIONAL: "Gender (Optional)",
    MALE: "Male",
    FEMALE: "Female",
    OTHER: "Other",
    BIRTH_DATE_OPTIONAL: "Birth Date (Optional)",
    CANNOT_BE_CHANGED: "Cannot be changed",
    SELECT_GENDER: "Select gender",

    // Post
    POST: "Post",
    POSTS: "Posts",
    NEW_POST: "New Post",
    TITLE: "Title",
    CONTENT: "Content",
    TAGS: "Tags",
    TAGS_COMMA_SEPARATED: "Tags (comma separated)",
    TAGS_PLACEHOLDER: "e.g. training, match, diet",
    CATEGORY: "Category",
    SELECT_CATEGORY: "Select category",
    VIEWS: "views",
    UPDATING_POST: "Updating post...",
    POST_UPDATED_SUCCESS: "Post updated successfully!",
    FAILED_TO_UPDATE_POST: "Failed to update post",
    FAILED_TO_LOAD_POST: "Failed to load post",
    LOGIN_TO_COMMENT: "to comment",
    NO_COMMENTS_BE_FIRST: "No comments yet. Be the first to comment!",
    TITLE_REQUIRED: "Title is required",
    CONTENT_REQUIRED: "Content is required",
    CATEGORY_REQUIRED: "Category is required",

    // Comment
    COMMENT: "Comment",
    COMMENTS: "Comments",
    ADD_COMMENT: "Add Comment",
    WRITE_REPLY: "Write a reply...",
    COMMENT_LIKED: "Comment liked!",
    COMMENT_UNLIKED: "Comment unliked!",
    COMMENT_DELETED: "Comment deleted!",
    FAILED_TO_LIKE_COMMENT: "Failed to like comment",
    FAILED_TO_DELETE_COMMENT: "Failed to delete comment",
    FAILED_TO_LOAD_REPLIES: "Failed to load replies",
    DELETE_COMMENT_CONFIRM: "Are you sure you want to delete this comment?",
    UNLIKE: "Unlike",

    // Profile & Admin
    PROFILE: "Profile",
    SETTINGS: "Settings",
    AVATAR: "Avatar",
    ADMIN_DASHBOARD: "Admin Dashboard",
    MANAGE_CATEGORIES_POSTS_USERS: "Manage categories, posts, and users",
    ABOUT: "About",
    EDIT_PROFILE: "Edit Profile",
    NAME: "Name",
    BIRTHDAY: "Birthday",
    GENDER: "Gender",
    MEMBER_SINCE: "Member since",
    JOINED: "Joined",
    POINTS: "Points",
    LIKES: "Likes",
    NO_POSTS_YET: "No posts yet",
    BACK_TO_PROFILE: "Back to Profile",
    POSTS_BY: "'s Posts",
    POST_SINGULAR: "post",
    POST_PLURAL: "posts",
    COMMENTS_BY: "'s Comments",
    COMMENT_SINGULAR: "comment",
    COMMENT_PLURAL: "comments",
    NO_COMMENTS_YET: "No comments yet",
    LIKES_LABEL: "likes",
    REPLIES_LABEL: "replies",
    LIKED_CONTENT: "Liked Content",
    LIKED_POSTS: "Liked Posts",
    LIKED_COMMENTS: "Liked Comments",
    NO_LIKED_POSTS: "No liked posts yet",
    NO_LIKED_COMMENTS: "No liked comments yet",
    ON: "on",
    // Avatar Upload
    AVATAR_UPLOAD: "Upload Avatar",
    AVATAR_UPLOAD_DESCRIPTION: "Upload your avatar image",
    AVATAR_UPLOAD_SUCCESS: "Avatar uploaded successfully!",
    AVATAR_UPLOAD_ERROR: "Failed to upload avatar",
    AVATAR_UPLOAD_SIZE_ERROR: "File size must be less than 5MB",
    AVATAR_UPLOAD_TYPE_ERROR: "Please select an image file",
    AVATAR_CHANGE: "Change Avatar",
    AVATAR_UPLOADING: "Uploading...",
  },

  ja: {
    // Application info
    APP_NAME: "ボクシング仲間の会",
    APP_SHORT_NAME: "BBW",
    APP_DESCRIPTION:
      "ボクシング仲間が世界中で考えや経験を共有するためのコミュニティ。",

    // Home page
    HOME_WELCOME: "BBWへようこそ",
    HOME_SUBTITLE: "あなたの考えをシェアし、他の人とつながりましょう",
    HOME_NO_POSTS: "まだ投稿がありません",
    HOME_CREATE_FIRST_POST: "最初の投稿を作成",

    // Common actions
    SAVE: "保存",
    CANCEL: "キャンセル",
    DELETE: "削除",
    EDIT: "編集",
    SUBMIT: "送信",
    LOADING: "読み込み中...",
    REPLY: "返信",
    LIKE: "いいね",
    VIEW: "表示",
    SHARE: "共有",
    SEE_MORE: "もっと見る",

    // Admin Management
    POSTS_MANAGEMENT: "投稿管理",
    USERS_MANAGEMENT: "ユーザー管理",
    CATEGORIES_MANAGEMENT: "カテゴリー管理",
    TOTAL: "合計",
    AUTHOR: "投稿者",
    CREATED: "作成日",
    ACTIONS: "操作",
    NO_POSTS_FOUND: "投稿が見つかりません",
    FAILED_TO_LOAD_POSTS: "投稿の読み込みに失敗しました",
    POST_DELETED_SUCCESS: "投稿を削除しました",
    FAILED_TO_DELETE_POST: "投稿の削除に失敗しました",
    PREVIOUS: "前へ",
    NEXT: "次へ",
    PAGE: "ページ",
    OF: "/",

    // Alert Dialog
    ARE_YOU_SURE: "本当によろしいですか？",
    DELETE_POST_CONFIRMATION:
      "この操作は取り消せません。投稿とすべてのコメントが完全に削除されます。",
    ALERT_CANNOT_BE_UNDONE: "この操作は取り消せません。",
    ALERT_USER_ID_REQUIRED: "ユーザーIDは必須です",
    ALERT_PASSWORD_REQUIRED: "パスワードは必須です",
    ALERT_USER_ID_CAN_ONLY_CONTAIN_ENGLISH_LETTERS_AND_NUMBERS:
      "ユーザーIDは英字と数字のみ使用できます",
    ALERT_INVALID_EMAIL_ADDRESS: "無効なメールアドレス",
    ALERT_NAME_MIN_LENGTH: "名前は2文字以上である必要があります",
    ALERT_NAME_MAX_LENGTH: "名前は50文字以下である必要があります",
    ALERT_NICKNAME_MAX_LENGTH: "ニックネームは20文字以下である必要があります",
    ALERT_EMAIL_REQUIRED: "メールアドレスは必須です",
    ALERT_EMAIL_TAKEN: "このメールアドレスは既に使用されています",
    ALERT_PASSWORD_MIN_LENGTH: "パスワードは6文字以上である必要があります",
    ALERT_PASSWORD_MAX_LENGTH: "パスワードは32文字以下である必要があります",
    ALERT_SLUG_REQUIRED: "Slugは必須です",
    ALERT_SLUG_MUST_BE_LOWERCASE_ALPHANUMERIC_WITH_HYPHENS:
      "Slugは小文字の英数字とハイフンのみ使用できます",
    ALERT_NAME_REQUIRED: "名前は必須です",
    ALERT_TITLE_REQUIRED: "タイトルは必須です",
    ALERT_CONTENT_REQUIRED: "内容は必須です",
    ALERT_CATEGORY_REQUIRED: "カテゴリーは必須です",
    ALERT_DESCRIPTION_MAX_LENGTH: "説明は1000文字以下である必要があります",
    ALERT_DISPLAY_ORDER_MIN: "表示順序は0以上である必要があります",
    ALERT_DISPLAY_ORDER_MAX: "表示順序は1000以下である必要があります",

    // Error messages
    ERROR_GENERIC: "エラーが発生しました。もう一度お試しください。",
    ERROR_UNAUTHORIZED: "この操作を実行する権限がありません。",
    ERROR_NOT_FOUND: "リクエストされたリソースが見つかりませんでした。",
    ERROR_INVALID_INPUT: "入力が無効です。データを確認してください。",
    ERROR_NETWORK: "ネットワークエラーです。接続を確認してください。",

    // Loading messages
    LOADING_POSTS: "投稿を読み込み中...",
    LOADING_COMMENTS: "コメントを読み込み中...",
    LOADING_USERS: "ユーザーを読み込み中...",
    LOADING_CATEGORIES: "カテゴリーを読み込み中...",
    LOADING_PROFILE: "プロフィールを読み込み中...",
    LOADING_ADMIN_DASHBOARD: "管理者ダッシュボードを読み込み中...",
    LOADING_ADMIN_CATEGORIES: "管理者カテゴリーを読み込み中...",
    LOADING_ADMIN_POSTS: "管理者投稿を読み込み中...",
    LOADING_ADMIN_USERS: "管理者ユーザーを読み込み中...",

    // Success messages
    SUCCESS_SAVED: "保存しました！",
    SUCCESS_DELETED: "削除しました！",
    SUCCESS_UPDATED: "更新しました！",
    SUCCESS_CREATED: "作成しました！",

    // Categories
    CATEGORY_GENERAL: "一般",
    CATEGORY_QUESTION: "質問",
    CATEGORY_DISCUSSION: "ディスカッション",
    CATEGORY_ANNOUNCEMENT: "お知らせ",

    // User roles
    ROLE_ADMIN: "管理者",
    ROLE_USER: "ユーザー",

    // Auth
    LOGIN: "ログイン",
    LOGOUT: "ログアウト",
    REGISTER: "登録",
    EMAIL: "メールアドレス",
    PASSWORD: "パスワード",
    USERNAME: "ユーザー名",
    ALREADY_HAVE_ACCOUNT: "すでにアカウントをお持ちですか？",
    DONT_HAVE_ACCOUNT: "アカウントをお持ちでないですか？",

    // Register Form
    CREATE_ACCOUNT: "アカウントを作成",
    ENTER_DETAILS_TO_REGISTER: "登録情報を入力してください",
    USERNAME_PLACEHOLDER: "最大12文字の英数字",
    USER_ID_TAKEN: "このユーザーIDは既に使用されています",
    USER_ID_AVAILABLE: "ユーザーIDは利用可能です",
    NAME_LABEL: "名前",
    NICKNAME_LABEL: "ニックネーム（任意）",
    CONFIRM_PASSWORD: "パスワード確認",
    PASSWORDS_DO_NOT_MATCH: "パスワードが一致しません",
    GENDER_OPTIONAL: "性別（任意）",
    MALE: "男性",
    FEMALE: "女性",
    OTHER: "その他",
    BIRTH_DATE_OPTIONAL: "生年月日（任意）",
    CANNOT_BE_CHANGED: "変更できません",
    SELECT_GENDER: "性別を選択",

    // Post
    POST: "投稿",
    POSTS: "投稿一覧",
    NEW_POST: "新規投稿",
    TITLE: "タイトル",
    CONTENT: "内容",
    TAGS: "タグ",
    TAGS_COMMA_SEPARATED: "タグ（カンマ区切り）",
    TAGS_PLACEHOLDER: "例：トレーニング、試合、ダイエット",
    CATEGORY: "カテゴリー",
    SELECT_CATEGORY: "カテゴリーを選択",
    VIEWS: "閲覧",
    UPDATING_POST: "投稿を更新中...",
    POST_UPDATED_SUCCESS: "投稿を更新しました！",
    FAILED_TO_UPDATE_POST: "投稿の更新に失敗しました",
    FAILED_TO_LOAD_POST: "投稿の読み込みに失敗しました",
    LOGIN_TO_COMMENT: "コメントする",
    NO_COMMENTS_BE_FIRST:
      "まだコメントがありません。最初にコメントしましょう！",
    TITLE_REQUIRED: "タイトルは必須です",
    CONTENT_REQUIRED: "内容は必須です",
    CATEGORY_REQUIRED: "カテゴリーは必須です",

    // Comment
    COMMENT: "コメント",
    COMMENTS: "コメント",
    ADD_COMMENT: "コメントを追加",
    WRITE_REPLY: "返信を書く...",
    COMMENT_LIKED: "コメントがいいねされました！",
    COMMENT_UNLIKED: "コメントが解除されました！",
    COMMENT_DELETED: "コメントが削除されました！",
    FAILED_TO_LIKE_COMMENT: "コメントのいいねに失敗しました",
    FAILED_TO_DELETE_COMMENT: "コメントの削除に失敗しました",
    FAILED_TO_LOAD_REPLIES: "返信の読み込みに失敗しました",
    DELETE_COMMENT_CONFIRM: "本当にこのコメントを削除しますか？",
    UNLIKE: "いいねを解除",

    // Profile & Admin
    PROFILE: "プロフィール",
    SETTINGS: "設定",
    AVATAR: "アバター",
    ADMIN_DASHBOARD: "管理者ダッシュボード",
    MANAGE_CATEGORIES_POSTS_USERS: "カテゴリー、投稿、ユーザーを管理",
    ABOUT: "について",
    EDIT_PROFILE: "プロフィールを編集",
    NAME: "名前",
    BIRTHDAY: "誕生日",
    GENDER: "性別",
    MEMBER_SINCE: "登録日",
    JOINED: "参加",
    POINTS: "ポイント",
    LIKES: "いいね",
    NO_POSTS_YET: "まだ投稿がありません",
    BACK_TO_PROFILE: "プロフィールに戻る",
    POSTS_BY: "の投稿",
    POST_SINGULAR: "件の投稿",
    POST_PLURAL: "件の投稿",
    COMMENTS_BY: "のコメント",
    COMMENT_SINGULAR: "件のコメント",
    COMMENT_PLURAL: "件のコメント",
    NO_COMMENTS_YET: "まだコメントがありません",
    LIKES_LABEL: "いいね",
    REPLIES_LABEL: "返信",
    LIKED_CONTENT: "いいねしたコンテンツ",
    LIKED_POSTS: "いいねした投稿",
    LIKED_COMMENTS: "いいねしたコメント",
    NO_LIKED_POSTS: "まだいいねした投稿がありません",
    NO_LIKED_COMMENTS: "まだいいねしたコメントがありません",
    ON: "の",
    // Avatar Upload
    AVATAR_UPLOAD: "アバターをアップロード",
    AVATAR_UPLOAD_DESCRIPTION: "アバター画像をアップロード",
    AVATAR_UPLOAD_SUCCESS: "アバターをアップロードしました！",
    AVATAR_UPLOAD_ERROR: "アバターのアップロードに失敗しました",
    AVATAR_UPLOAD_SIZE_ERROR: "ファイルサイズは5MB以下にしてください",
    AVATAR_UPLOAD_TYPE_ERROR: "画像ファイルを選択してください",
    AVATAR_CHANGE: "アバターを変更",
    AVATAR_UPLOADING: "アップロード中...",
  },

  "zh-CN": {
    // Application info
    APP_NAME: "拳击交流同好会",
    APP_SHORT_NAME: "拳交会",
    APP_DESCRIPTION:
      "拳击交流同好会，一个让拳击爱好者们分享想法和经验的全球社区。",

    // Home page
    HOME_WELCOME: "欢迎来到拳交会",
    HOME_SUBTITLE: "分享您的想法，与他人建立联系",
    HOME_NO_POSTS: "还没有帖子",
    HOME_CREATE_FIRST_POST: "创建第一个帖子",

    // Common actions
    SAVE: "保存",
    CANCEL: "取消",
    DELETE: "删除",
    EDIT: "编辑",
    SUBMIT: "提交",
    LOADING: "加载中...",
    REPLY: "回复",
    LIKE: "点赞",
    VIEW: "查看",
    SHARE: "分享",
    SEE_MORE: "查看更多",

    // Admin Management
    POSTS_MANAGEMENT: "帖子管理",
    USERS_MANAGEMENT: "用户管理",
    CATEGORIES_MANAGEMENT: "分类管理",
    TOTAL: "总计",
    AUTHOR: "作者",
    CREATED: "创建时间",
    ACTIONS: "操作",
    NO_POSTS_FOUND: "未找到帖子",
    FAILED_TO_LOAD_POSTS: "加载帖子失败",
    POST_DELETED_SUCCESS: "帖子删除成功",
    FAILED_TO_DELETE_POST: "删除帖子失败",
    PREVIOUS: "上一页",
    NEXT: "下一页",
    PAGE: "第",
    OF: "页，共",

    // Alert Dialog
    ARE_YOU_SURE: "您确定吗？",
    DELETE_POST_CONFIRMATION: "此操作无法撤消。这将永久删除帖子及其所有评论。",
    ALERT_CANNOT_BE_UNDONE: "此操作无法撤消。",
    ALERT_USER_ID_REQUIRED: "用户ID为必填项",
    ALERT_PASSWORD_REQUIRED: "密码为必填项",
    ALERT_USER_ID_CAN_ONLY_CONTAIN_ENGLISH_LETTERS_AND_NUMBERS:
      "用户ID只能包含英文和数字",
    ALERT_INVALID_EMAIL_ADDRESS: "无效的电子邮件地址",
    ALERT_NAME_MIN_LENGTH: "姓名必须至少2个字符",
    ALERT_NAME_MAX_LENGTH: "姓名必须最多50个字符",
    ALERT_NICKNAME_MAX_LENGTH: "昵称必须最多20个字符",
    ALERT_EMAIL_REQUIRED: "邮箱为必填项",
    ALERT_EMAIL_TAKEN: "此邮箱已注册",
    ALERT_PASSWORD_MIN_LENGTH: "密码必须至少6个字符",
    ALERT_PASSWORD_MAX_LENGTH: "密码必须最多32个字符",
    ALERT_SLUG_REQUIRED: "Slug为必填项",
    ALERT_SLUG_MUST_BE_LOWERCASE_ALPHANUMERIC_WITH_HYPHENS:
      "Slug必须为小写字母和数字，并且只能包含连字符",
    ALERT_NAME_REQUIRED: "名称为必填项",
    ALERT_TITLE_REQUIRED: "标题为必填项",
    ALERT_CONTENT_REQUIRED: "内容为必填项",
    ALERT_CATEGORY_REQUIRED: "分类为必填项",
    ALERT_DESCRIPTION_MAX_LENGTH: "描述必须最多1000个字符",
    ALERT_DISPLAY_ORDER_MIN: "显示顺序必须至少0",
    ALERT_DISPLAY_ORDER_MAX: "显示顺序必须最多1000",

    // Error messages
    ERROR_GENERIC: "出错了，请重试。",
    ERROR_UNAUTHORIZED: "您没有权限执行此操作。",
    ERROR_NOT_FOUND: "未找到请求的资源。",
    ERROR_INVALID_INPUT: "输入无效，请检查您的数据。",
    ERROR_NETWORK: "网络错误，请检查您的连接。",

    // Loading messages
    LOADING_POSTS: "帖子加载中...",
    LOADING_COMMENTS: "评论加载中...",
    LOADING_USERS: "用户加载中...",
    LOADING_CATEGORIES: "分类加载中...",
    LOADING_PROFILE: "个人资料加载中...",
    LOADING_ADMIN_DASHBOARD: "管理员控制台加载中...",
    LOADING_ADMIN_CATEGORIES: "管理员分类加载中...",
    LOADING_ADMIN_POSTS: "管理员帖子加载中...",
    LOADING_ADMIN_USERS: "管理员用户加载中...",

    // Success messages
    SUCCESS_SAVED: "保存成功！",
    SUCCESS_DELETED: "删除成功！",
    SUCCESS_UPDATED: "更新成功！",
    SUCCESS_CREATED: "创建成功！",

    // Categories
    CATEGORY_GENERAL: "综合",
    CATEGORY_QUESTION: "提问",
    CATEGORY_DISCUSSION: "讨论",
    CATEGORY_ANNOUNCEMENT: "公告",

    // User roles
    ROLE_ADMIN: "管理员",
    ROLE_USER: "用户",

    // Auth
    LOGIN: "登录",
    LOGOUT: "登出",
    REGISTER: "注册",
    EMAIL: "邮箱",
    PASSWORD: "密码",
    USERNAME: "用户名",
    ALREADY_HAVE_ACCOUNT: "已有账号？",
    DONT_HAVE_ACCOUNT: "还没有账号？",

    // Register Form
    CREATE_ACCOUNT: "创建账号",
    CANNOT_BE_CHANGED: "无法更改",
    ENTER_DETAILS_TO_REGISTER: "输入您的详细信息以注册",
    USERNAME_PLACEHOLDER: "最多12个字母数字字符",
    USER_ID_TAKEN: "此用户ID已被占用",
    USER_ID_AVAILABLE: "用户ID可用",
    NAME_LABEL: "姓名",
    NICKNAME_LABEL: "昵称（可选）",
    CONFIRM_PASSWORD: "确认密码",
    PASSWORDS_DO_NOT_MATCH: "密码不匹配",
    GENDER_OPTIONAL: "性别（可选）",
    SELECT_GENDER: "选择性别",
    MALE: "男",
    FEMALE: "女",
    OTHER: "其他",
    BIRTH_DATE_OPTIONAL: "出生日期（可选）",

    // Post
    POST: "帖子",
    POSTS: "帖子列表",
    NEW_POST: "新帖子",
    TITLE: "标题",
    CONTENT: "内容",
    TAGS: "标签",
    TAGS_COMMA_SEPARATED: "标签（逗号分隔）",
    TAGS_PLACEHOLDER: "例：训练、比赛、饮食",
    CATEGORY: "分类",
    SELECT_CATEGORY: "选择分类",
    VIEWS: "浏览",
    UPDATING_POST: "更新帖子中...",
    POST_UPDATED_SUCCESS: "帖子更新成功！",
    FAILED_TO_UPDATE_POST: "更新帖子失败",
    FAILED_TO_LOAD_POST: "加载帖子失败",
    LOGIN_TO_COMMENT: "评论",
    NO_COMMENTS_BE_FIRST: "还没有评论。成为第一个评论的人！",
    TITLE_REQUIRED: "标题为必填项",
    CONTENT_REQUIRED: "内容为必填项",
    CATEGORY_REQUIRED: "分类为必填项",

    // Comment
    COMMENT: "评论",
    COMMENTS: "评论",
    ADD_COMMENT: "添加评论",
    WRITE_REPLY: "回复...",
    COMMENT_LIKED: "评论被点赞！",
    COMMENT_UNLIKED: "评论被取消点赞！",
    COMMENT_DELETED: "评论被删除！",
    FAILED_TO_LIKE_COMMENT: "评论点赞失败",
    FAILED_TO_DELETE_COMMENT: "评论删除失败",
    FAILED_TO_LOAD_REPLIES: "回复加载失败",
    DELETE_COMMENT_CONFIRM: "你确定要删除这条评论吗？",
    UNLIKE: "取消点赞",

    // Profile & Admin
    PROFILE: "个人资料",
    SETTINGS: "设置",
    AVATAR: "头像",
    ADMIN_DASHBOARD: "管理员控制台",
    MANAGE_CATEGORIES_POSTS_USERS: "管理分类、帖子和用户",
    ABOUT: "关于",
    EDIT_PROFILE: "编辑个人资料",
    NAME: "姓名",
    BIRTHDAY: "生日",
    GENDER: "性别",
    MEMBER_SINCE: "注册时间",
    JOINED: "加入",
    POINTS: "积分",
    LIKES: "点赞",
    NO_POSTS_YET: "还没有帖子",
    BACK_TO_PROFILE: "返回个人资料",
    POSTS_BY: "的帖子",
    POST_SINGULAR: "个帖子",
    POST_PLURAL: "个帖子",
    COMMENTS_BY: "的评论",
    COMMENT_SINGULAR: "条评论",
    COMMENT_PLURAL: "条评论",
    NO_COMMENTS_YET: "还没有评论",
    LIKES_LABEL: "点赞",
    REPLIES_LABEL: "回复",
    LIKED_CONTENT: "点赞的内容",
    LIKED_POSTS: "点赞的帖子",
    LIKED_COMMENTS: "点赞的评论",
    NO_LIKED_POSTS: "还没有点赞的帖子",
    NO_LIKED_COMMENTS: "还没有点赞的评论",
    ON: "在",
    // Avatar Upload
    AVATAR_UPLOAD: "上传头像",
    AVATAR_UPLOAD_DESCRIPTION: "上传您的头像图片",
    AVATAR_UPLOAD_SUCCESS: "头像上传成功！",
    AVATAR_UPLOAD_ERROR: "头像上传失败",
    AVATAR_UPLOAD_SIZE_ERROR: "文件大小必须小于5MB",
    AVATAR_UPLOAD_TYPE_ERROR: "请选择一个图片文件",
    AVATAR_CHANGE: "更改头像",
    AVATAR_UPLOADING: "上传中...",
  },

  "zh-TW": {
    // Application info
    APP_NAME: "拳擊交流同好會",
    APP_SHORT_NAME: "拳交會",
    APP_DESCRIPTION:
      "拳擊交流同好會，一個讓拳擊愛好者們分享想法和經驗的全球社區。",
    // Home page
    HOME_WELCOME: "歡迎來到拳交會",
    HOME_SUBTITLE: "分享您的想法，與他人建立聯繫",
    HOME_NO_POSTS: "還沒有帖子",
    HOME_CREATE_FIRST_POST: "創建第一個帖子",
    // Common actions
    SAVE: "保存",
    CANCEL: "取消",
    DELETE: "刪除",
    EDIT: "編輯",
    SUBMIT: "提交",
    LOADING: "加載中...",
    REPLY: "回复",
    LIKE: "點贊",
    VIEW: "查看",
    SHARE: "分享",
    SEE_MORE: "查看更多",
    // Admin Management
    POSTS_MANAGEMENT: "帖子管理",
    USERS_MANAGEMENT: "用戶管理",
    CATEGORIES_MANAGEMENT: "分類管理",
    TOTAL: "總計",
    AUTHOR: "作者",
    CREATED: "創建時間",
    ACTIONS: "操作",
    NO_POSTS_FOUND: "未找到帖子",
    FAILED_TO_LOAD_POSTS: "加載帖子失敗",
    POST_DELETED_SUCCESS: "帖子刪除成功",
    FAILED_TO_DELETE_POST: "刪除帖子失敗",
    PREVIOUS: "上一頁",
    NEXT: "下一頁",
    PAGE: "第",
    OF: "頁，共",
    // Alert Dialog
    ARE_YOU_SURE: "您確定嗎？",
    DELETE_POST_CONFIRMATION: "此動作無法還原。將永久刪除貼文及所有留言。",
    ALERT_CANNOT_BE_UNDONE: "此動作無法還原。",
    ALERT_USER_ID_REQUIRED: "使用者ID為必填項",
    ALERT_PASSWORD_REQUIRED: "密碼為必填項",
    ALERT_USER_ID_CAN_ONLY_CONTAIN_ENGLISH_LETTERS_AND_NUMBERS:
      "使用者ID只能包含英文字母和數字",
    ALERT_INVALID_EMAIL_ADDRESS: "無效的電子郵件地址",
    ALERT_NAME_MIN_LENGTH: "姓名至少需有2個字元",
    ALERT_NAME_MAX_LENGTH: "姓名最多只能有50個字元",
    ALERT_NICKNAME_MAX_LENGTH: "暱稱最多只能有20個字元",
    ALERT_EMAIL_REQUIRED: "電子郵件為必填項",
    ALERT_EMAIL_TAKEN: "此電子郵件地址已註冊",
    ALERT_PASSWORD_MIN_LENGTH: "密碼至少需有6個字元",
    ALERT_PASSWORD_MAX_LENGTH: "密碼最多只能有32個字元",
    ALERT_SLUG_REQUIRED: "Slug為必填項",
    ALERT_SLUG_MUST_BE_LOWERCASE_ALPHANUMERIC_WITH_HYPHENS:
      "Slug 必須全為小寫字母、數字，且只能包含連字號",
    ALERT_NAME_REQUIRED: "名稱為必填項",
    ALERT_TITLE_REQUIRED: "標題為必填項",
    ALERT_CONTENT_REQUIRED: "內容為必填項",
    ALERT_CATEGORY_REQUIRED: "分類為必填項",
    ALERT_DESCRIPTION_MAX_LENGTH: "描述最多只能有1000個字元",
    ALERT_DISPLAY_ORDER_MIN: "顯示順序至少為0",
    ALERT_DISPLAY_ORDER_MAX: "顯示順序最多只能為1000",

    // Error messages
    ERROR_GENERIC: "發生錯誤。請再試一次。",
    ERROR_UNAUTHORIZED: "您沒有權限執行此操作。",
    ERROR_NOT_FOUND: "未找到請求的資源。",
    ERROR_INVALID_INPUT: "輸入無效。請檢查您的數據。",
    ERROR_NETWORK: "網絡錯誤。請檢查您的連接。",
    // Loading messages
    LOADING_POSTS: "加載帖子中...",
    LOADING_COMMENTS: "加載評論中...",
    LOADING_USERS: "加載用戶中...",
    LOADING_CATEGORIES: "加載分類中...",
    LOADING_PROFILE: "加載個人資料中...",
    LOADING_ADMIN_DASHBOARD: "加載管理員控制台中...",
    LOADING_ADMIN_CATEGORIES: "加載管理員分類中...",
    LOADING_ADMIN_POSTS: "加載管理員帖子中...",
    LOADING_ADMIN_USERS: "加載管理員用戶中...",
    // Success messages
    SUCCESS_SAVED: "保存成功！",
    SUCCESS_DELETED: "刪除成功！",
    SUCCESS_UPDATED: "更新成功！",
    SUCCESS_CREATED: "創建成功！",
    // Categories
    CATEGORY_GENERAL: "一般",
    CATEGORY_QUESTION: "問題",
    CATEGORY_DISCUSSION: "討論",
    CATEGORY_ANNOUNCEMENT: "公告",
    // User roles
    ROLE_ADMIN: "管理員",
    ROLE_USER: "用戶",
    // Auth
    LOGIN: "登錄",
    LOGOUT: "登出",
    REGISTER: "註冊",
    EMAIL: "電子郵件",
    PASSWORD: "密碼",
    USERNAME: "用戶名",
    ALREADY_HAVE_ACCOUNT: "已經有帳戶了嗎？",
    DONT_HAVE_ACCOUNT: "沒有帳戶嗎？",
    // Register Form
    CREATE_ACCOUNT: "註冊帳戶",
    ENTER_DETAILS_TO_REGISTER: "請輸入詳細信息",
    USERNAME_PLACEHOLDER: "最大12個字符的英數字",
    USER_ID_TAKEN: "此用戶ID已被使用",
    USER_ID_AVAILABLE: "此用戶ID可用",
    NAME_LABEL: "姓名",
    NICKNAME_LABEL: "暱稱（可選）",
    CONFIRM_PASSWORD: "確認密碼",
    PASSWORDS_DO_NOT_MATCH: "密碼不匹配",
    GENDER_OPTIONAL: "性別（可選）",
    MALE: "男性",
    FEMALE: "女性",
    OTHER: "其他",
    BIRTH_DATE_OPTIONAL: "出生日期（可選）",
    CANNOT_BE_CHANGED: "無法更改",
    SELECT_GENDER: "選擇性別",
    // Post
    POST: "帖子",
    POSTS: "帖子列表",
    NEW_POST: "新帖子",
    TITLE: "標題",
    CONTENT: "內容",
    TAGS: "標籤",
    TAGS_COMMA_SEPARATED: "標籤（逗號分隔）",
    TAGS_PLACEHOLDER: "例如：訓練、比賽、減肥",
    CATEGORY: "分類",
    SELECT_CATEGORY: "選擇分類",
    VIEWS: "查看",
    UPDATING_POST: "更新帖子中...",
    POST_UPDATED_SUCCESS: "帖子更新成功！",
    FAILED_TO_UPDATE_POST: "帖子更新失敗",
    FAILED_TO_LOAD_POST: "帖子加載失敗",
    LOGIN_TO_COMMENT: "評論",
    NO_COMMENTS_BE_FIRST: "還沒有評論。成為第一個評論的人！",
    TITLE_REQUIRED: "標題為必填項",
    CONTENT_REQUIRED: "內容為必填項",
    CATEGORY_REQUIRED: "分類為必填項",
    // Comment
    COMMENT: "評論",
    COMMENTS: "評論",
    ADD_COMMENT: "添加評論",
    WRITE_REPLY: "回复...",
    COMMENT_LIKED: "評論被點讚！",
    COMMENT_UNLIKED: "評論被取消點讚！",
    COMMENT_DELETED: "評論被刪除！",
    FAILED_TO_LIKE_COMMENT: "評論點讚失敗",
    FAILED_TO_DELETE_COMMENT: "評論刪除失敗",
    FAILED_TO_LOAD_REPLIES: "回复加載失敗",
    DELETE_COMMENT_CONFIRM: "你確定要刪除這條評論嗎？",
    UNLIKE: "取消點讚",
    // Profile & Admin
    PROFILE: "個人資料",
    SETTINGS: "設定",
    AVATAR: "頭像",
    ADMIN_DASHBOARD: "管理員控制台",
    MANAGE_CATEGORIES_POSTS_USERS: "管理分類、帖子、用戶",
    ABOUT: "關於",
    EDIT_PROFILE: "編輯個人資料",
    NAME: "姓名",
    BIRTHDAY: "出生日期",
    GENDER: "性別",
    MEMBER_SINCE: "會員時間",
    JOINED: "加入",
    POINTS: "點數",
    LIKES: "點讚",
    NO_POSTS_YET: "還沒有帖子",
    BACK_TO_PROFILE: "返回個人資料",
    POSTS_BY: "的帖子",
    POST_SINGULAR: "帖子",
    POST_PLURAL: "帖子",
    COMMENTS_BY: "的評論",
    COMMENT_SINGULAR: "評論",
    COMMENT_PLURAL: "評論",
    NO_COMMENTS_YET: "還沒有評論",
    LIKES_LABEL: "點讚",
    REPLIES_LABEL: "回复",
    LIKED_CONTENT: "點讚的內容",
    LIKED_POSTS: "點讚的帖子",
    LIKED_COMMENTS: "點讚的評論",
    NO_LIKED_POSTS: "還沒有點讚的帖子",
    NO_LIKED_COMMENTS: "還沒有點讚的評論",
    ON: "在",
    // Avatar Upload
    AVATAR_UPLOAD: "上傳頭像",
    AVATAR_UPLOAD_DESCRIPTION: "上傳您的頭像圖片",
    AVATAR_UPLOAD_SUCCESS: "頭像上傳成功！",
    AVATAR_UPLOAD_ERROR: "頭像上傳失敗",
    AVATAR_UPLOAD_SIZE_ERROR: "文件大小必須小於5MB",
    AVATAR_UPLOAD_TYPE_ERROR: "請選擇一個圖片文件",
    AVATAR_CHANGE: "更改頭像",
    AVATAR_UPLOADING: "上傳中...",
  },
} as const;

// Helper function to get translated text, default to Japanese if no language is provided
export const t = (
  key: keyof typeof TRANSLATIONS.en,
  lang?: Language | null
): string => {
  return TRANSLATIONS[lang ?? "ja"][key] ?? key;
};

export type PostCategory = (typeof APP_CONSTANTS.POST_CATEGORIES)[number];
